spring.application.name: loadbalancer
spring.config.import:
  - optional:nacos:${spring.application.name}.yaml

spring.cloud.nacos.discovery.server-addr: http://localhost:8848
spring.cloud.nacos.discovery.username: nacos
spring.cloud.nacos.discovery.password: nacos
spring.cloud.nacos.discovery.namespace: 048fb675-2fb2-4f44-a242-9797674be6d5
spring.cloud.nacos.discovery.service: ${spring.application.name}

spring.cloud.nacos.config.server-addr: http://localhost:8848
spring.cloud.nacos.config.username: nacos
spring.cloud.nacos.config.password: nacos
spring.cloud.nacos.config.namespace: 048fb675-2fb2-4f44-a242-9797674be6d5
spring.cloud.nacos.config.file-extension: yaml

spring:
  main:
    allow-bean-definition-overriding: true