apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: petclinic
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: spring2go/spring-petclinic:1.0.0.RELEASE
